### PR TITLE
add mne stuff

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
- add extended notebook
    - stats examples
    - more TFR stuff
    - more docs
    - better notebook backend organisation

- add new example binary file (old one has shifted time stamps)

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
I've added the example EEG file as a binary, hope that's ok?

**Comment by jona-sassenhagen** [comment]
@miykael , if I understand this correctly, this means for the sake of avoiding redundancy, you'd remove the files locally and rebuild the image?

**Comment by miykael** [comment]
@jona-sassenhagen, thanks for the PR. Out of experience I would like to avoid to add the EEG binary to github. Because if I'm not mistaken, even if we later delete or change the file again, it will keep the diff files in the log and cause the cloning of the repo to become bigger and bigger.

Before I merge the PR, could you delte the EEG file? I will directly at it to the new docker image.

**Comment by jona-sassenhagen** [comment]
I've deleted the binary, thanks.

**Comment by miykael** [comment]
Perfect, will merge the content.

**Pull request merged**
