### PR TITLE
update readme.md & program.ipynb

### PR DESCRIPTION
**Pull request by PeerHerholz**
- include link to workshop hp in readme.md
- added some suggestions & questions in program.ipynb

### CODE REVIEW

**Comment by miykael** [comment]
@PeerHerholz, thanks for the input. Here my comments.

**About the slides** - I didn't intend to communicate real content in the slides where I also have notebooks, but just wanted 2 additional slides for teaching/course purposes, to say: 1. how long they should work on it; 2. main points communicated.

I was hesitant to use the `nipype_tutorial` **docker image** for just the python part. Because it's rather big. But it's a good idea. I will set up a notebook that's based on nipype_tutorial and adds missing softwares.

About **neuroviz**, I tried to incorporate all of their content in my notebooks. I didn't just link to them, as I didn't see a smooth integration. But I'm open to suggestions.

About **nilearn**, I took some examples from http://nilearn.github.io/auto_examples/index.html and put them in the notebooks. See [x_nilearn_image_manipulation.ipynb](https://github.com/miykael/workshops/blob/master/180309_marburg/notebooks/neuroimaging/x_nilearn_image_manipulation.ipynb) and [x_nilearn_plotting_example.ipynb](https://github.com/miykael/workshops/blob/master/180309_marburg/notebooks/neuroimaging/x_nilearn_plotting_example.ipynb).

**Comment by miykael** [comment]
@PeerHerholz - yes, I already tried the exercises and rubberband extentsions. They are actually already used in `nipype_tutorial` at certain places. It's really usefull for classes.

About the docker image, hmm... pysurfer only works in python 2.7. Therefore it might make sense to create another docker image (much smaller, only ~2-3GB) that only includes MNE? No, you're right. Let's put everything in a `workshop` image. And we just switch between the environments.

**nilearn**: Good point! .orthoview(), T1 & EPI plotting and masking is already (or will be) in the [nibabel and nilearn notebooks](https://github.com/miykael/workshops/blob/master/180309_marburg/notebooks/neuroimaging/01_nibabel_nilearn.ipynb).

**Comment by miykael** [comment]
@PeerHerholz - just created the new docker image. It can be found [here](https://hub.docker.com/r/miykael/workshop_marburg/). To open the normal image, just run

``docker run -it --rm -p 8888:8888 miykael/workshop_marburg``

To run it for the MNE part of the course add ``./mne.sh``:

``docker run -it --rm -p 8888:8888 miykael/workshop_marburg ./mne.sh``

If the MNE group has notebooks, we could directly add them into the docker image.

**Comment by PeerHerholz** [comment]
@miykael - played around with the docker image and I think it's looking great!

Yeah, I already told them to let us know and share their notebooks asap!

**Pull request merged**
